services:
  server:
    environment:
      INTELLIGRATE_GPU_ENABLED: true

  ollama:
    profiles: []    # override - remove profile so ollama starts locally
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # use gpu
              capabilities: [gpu]

  server-chatbot:
    environment:
      GPU_ENABLED: true
      USE_GEMINI_EMBEDDINGS: false # use ollama embeddings locally
    depends_on:
      ollama:
        condition: service_healthy
