services:
  server:
    environment:
      INTELLIGRATE_GPU_ENABLED: true

  ollama:
    deploy: 
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # use gpu
              capabilities: [gpu]

  server-chatbot:
    environment:
      GPU_ENABLED: true
