import { describe, expect, it } from "vitest";
import {
  buildResourceStats,
  createDefaultResourceThreads,
  enrichResources,
  filterResources,
  inferResourceTopic,
  inferResourceType,
  inferResourceVersion,
  normalizeResourceName,
} from "../../apps/client/src/features/room/resourceWorkspace.js";

const room = { academicTerm: "2026/2027 S1", moduleCode: "CS2040S" };

describe("resource workspace helpers", () => {
  // Checks automatic metadata inference for uploaded resource names. These
  // helpers power Resources and Intelligrate labels, so filenames should produce
  // useful type/topic/version metadata without manual user input.
  it("infers resource metadata from filenames", () => {
    expect(inferResourceType({ originalName: "Lecture 03 Sorting.pdf" })).toBe("Lecture Notes");
    expect(inferResourceType({ originalName: "CS2040S Final Paper.pdf" })).toBe("Past Year Paper");
    expect(inferResourceTopic({ originalName: "CS2040S Lecture Graph Traversal.pdf" }, room)).toBe("graph traversal");
    expect(inferResourceVersion("Notes Version 2.pdf")).toBe("v2");
    expect(normalizeResourceName("Notes v2.pdf")).toBe("notes");
  });

  // Simulates two related uploads and confirms enrichment adds the fields used
  // by the Resources table, search, duplicate indicators, and contributor
  // display. This guards against regressions in app-side resource organization.
  it("enriches resources with searchable tags, contributor, and duplicate metadata", () => {
    const enriched = enrichResources(
      [
        {
          id: "r1",
          originalName: "Lecture 1 Graphs.pdf",
          folder: "Lecture Notes",
          uploader: { name: "Fleming" },
        },
        {
          id: "r2",
          originalName: "Lecture 1 Graphs v2.pdf",
          folder: "Lecture Notes",
          uploader: { name: "Fleming" },
        },
      ],
      room,
    );

    expect(enriched[0].metadata).toMatchObject({
      contributor: "Fleming",
      duplicateCount: 2,
      module: "CS2040S",
      resourceType: "Lecture Notes",
      semester: "2026/2027 S1",
      type: "Lecture Notes",
    });
    expect(enriched[0].searchText).toContain("graphs");
    expect(buildResourceStats(enriched)).toEqual({ total: 2, types: 1, duplicates: 1 });
  });

  // Covers the main Resources filters: folder navigation, semantic file type,
  // and free-text search. The goal is to catch cases where one filter silently
  // ignores the metadata generated by enrichment.
  it("filters enriched resources by folder, semantic type, and search", () => {
    const enriched = enrichResources(
      [
        { id: "r1", originalName: "Tutorial 2 Trees.pdf", folder: "Tutorials" },
        { id: "r2", originalName: "Formula Cheatsheet.pdf", folder: "Reference" },
      ],
      room,
    );

    expect(filterResources(enriched, { folder: "Tutorials" })).toHaveLength(1);
    expect(filterResources(enriched, { type: "Cheatsheet" })[0].id).toBe("r2");
    expect(filterResources(enriched, { query: "trees" })[0].id).toBe("r1");
  });

  // Verifies default discussion starters are generated from resource type/name.
  // These thread prompts should remain helpful starting points instead of
  // becoming generic or empty when a new resource is opened.
  it("creates useful discussion starters per resource type", () => {
    expect(createDefaultResourceThreads({ id: "tutorial", displayName: "Tutorial 1.pdf" }).map((item) => item.title)).toContain("Q1 discussion");
    expect(createDefaultResourceThreads({ id: "notes", displayName: "Lecture 1.pdf" }).map((item) => item.title)).toContain("Overview");
  });
});
