name: Docker Compose Test

on:
  pull_request:
    branches: [main]
    paths:
      - "apps/**"
      - "services/**"
      - "docker-compose.yaml"
      - "!**.md"
      - "!services/server-chatbot/static/**"


  push:
    branches: [main]
    paths:
      - "apps/**"
      - "services/**"
      - "docker-compose.yaml"
      - "!**.md"
      - "!services/server-chatbot/static/**"

jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create .env
      run: cp .env.example .env

    - name: Build containers
      run: docker compose build

    - name: Start Container
      run: docker compose up -d

    - name: on fail
      if: failure()
      run: docker compose logs --tail=200

    - name: Shutdown
      if: always()
      run: docker compose down -v